version: '3.8'

services:
  traefik:
    image: traefik:2.6.0
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - '80:80'
      - '443:443'
    labels:
      # Enable Traefik
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      # Automatic HTTP to HTTPS redirect
      - 'traefik.http.middlewares.https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.https-redirect.rule=PathPrefix(`/`)'
      - 'traefik.http.routers.https-redirect.entryPoints=http'
      - 'traefik.http.routers.https-redirect.middlewares=https-redirect'
      # Dashboard
      - 'traefik.http.routers.dashboard.rule=Host(`traefik.${HOSTNAME}`)'
      - 'traefik.http.routers.dashboard.service=api@internal'
      - 'traefik.http.routers.dashboard.entrypoints=https'
      - 'traefik.http.routers.dashboard.tls=true'
      - 'traefik.http.routers.dashboard.tls.certresolver=default'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json

networks:
  traefik:
    name: traefik
