global:
  sendAnonymousUsage: false

api:
  dashboard: true

entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'

providers:
  docker:
    endpoint: 'unix:///var/run/docker.sock'
    exposedByDefault: false

certificatesResolvers:
  default:
    acme:
      email: email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: http
